Add v0.20 release schemas
AbstractSDK/schemas pull request #28
Opened 2023-12-26 16:46 UTC by CyberHoward

see title

2023-12-26 17:17 UTC, h0tw4t3r requested changes
Can we have a common format of how the contract schema file is named?

Here it's either `module-schema.json` or `${namespace}-${module}.json`.

Is there any reason for them to be different?

2023-12-27 16:47 UTC, dalechyn requested changes

2023-12-27 16:47 UTC, dalechyn commented on abstract/abstract-adapter/0.20.0/adapter-schema.json
the file should be named `abstract-adapter.json`.

2023-12-27 16:47 UTC, dalechyn commented on abstract/abstract-app/0.20.0/app-schema.json
the file should be named `abstract-app.json`.

2023-12-27 17:02 UTC, dalechyn commented on abstract/abstract-adapter/0.20.0/adapter-schema.json
actually this scheme doesn't work with ts-codegen.

2023-12-27 17:02 UTC, dalechyn commented on abstract/abstract-app/0.20.0/app-schema.json
actually this scheme doesn't work with ts-codegen.

2023-12-28 09:43 UTC, merged